book/urls.py
from django.contrib import admin
from django.urls import path
from addresses.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path("addresses/add/", AddPersonView.as_view(), name="add_person"),
    path("addresses/all/", GetAllPersonsView.as_view(), name="all"),
    path("addresses/contact_info/<int:id>/", ContactInfoView.as_view(), name="contact_info"),
    path("addresses/edit_cocntact/<int:pk>/", ContactEditView.as_view(), name="edit_contact"),
    path("addresses/del_cocntact/<int:pk>/", ContactDeleteView.as_view(), name="delete_contact"),
    path("addresses/add_group/", CreateGroupView.as_view(), name="add_group"),
    path("addresses/all_groups/", GroupListView.as_view(), name="all_groups"),
    path("addresses/group_info/<int:id>", GroupInfoView.as_view(), name="group_info"),
    path("addresses/edit_group/<int:pk>/", EditGroupView.as_view(), name="edit_group"),
    path("addresses/del_group/<int:pk>/", GroupDeleteView.as_view(), name="delete_group"),
    path("", GetStartedView.as_view(), name="index")
]

addresses/models.py
from django.db import models

TYPES = (
    (1, 'domowy'),
    (2, 'służbowy'),
    (3, 'faks'),
    (4, 'inny'),
)


class Address(models.Model):
    city = models.CharField(max_length=64, verbose_name=u"Miasto")
    street = models.CharField(max_length=64, verbose_name=u"Ulica")
    street_number = models.CharField(max_length=8, verbose_name=u"Nr domu")
    flat_number = models.CharField(max_length=8, verbose_name=u"Nr mieszkania")

    def __str__(self):
        return f"ul./al. {self.street} nr {self.flat_number} m. {self.street_number} {self.city}"


class Group(models.Model):
    group_name = models.CharField(max_length=16, verbose_name=u"Nazwa")
    group_desc = models.TextField(verbose_name=u"Opis")

    def __str__(self):
        return f"{self.group_name}"


class Person(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    description = models.TextField()
    address = models.ForeignKey(Address, null=True, blank=True, on_delete=models.SET_NULL)
    groups = models.ManyToManyField(Group, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class PhoneNumber(models.Model):
    p_num = models.CharField(max_length=16, verbose_name=u"Numer telefonu")
    p_type = models.IntegerField(choices=TYPES, verbose_name=u"Rodzaj telefonu")
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def __str__(self):
        return f"telefon: {self.p_num} {self.p_type}"


class EmailAddress(models.Model):
    mail = models.EmailField(verbose_name=u"Adres email")
    m_type = models.IntegerField(choices=TYPES, verbose_name=u"Rodzaj maila")
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def __str__(self):
        return f"mail: {self.mail} {self.m_type}"

addresses/forms.py
from django import forms
from django.forms import inlineformset_factory, ModelMultipleChoiceField, CheckboxSelectMultiple

from addresses.models import *


class AddPersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = "first_name", "last_name", "description", "groups"

class AddEmailForm(forms.ModelForm):
    class Meta:
        model = EmailAddress
        fields = "__all__"


class AddPhoneForm(forms.ModelForm):
    class Meta:
        model = PhoneNumber
        fields = "__all__"


class AddAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = "__all__"


PhoneFormSet = inlineformset_factory(Person, PhoneNumber, fields='__all__', extra=1)
EmailFormSet = inlineformset_factory(Person, EmailAddress, fields='__all__', extra=1)

addresses/views.py
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import UpdateView, DeleteView, CreateView, ListView, DetailView

from .forms import *
from .models import *
# Create your views here.

class GetStartedView(View):
    def get(self, request):
        return render(request, "addresses/index.html", locals())

class AddPersonView(CreateView):
    model = Person
    fields = ['first_name', 'last_name', 'description', 'groups']
    template_name = "addresses/add_person.html"
    success_url = reverse_lazy("all")

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        phone_formset = PhoneFormSet()
        email_formset = EmailFormSet()
        address_form = AddAddressForm()
        return self.render_to_response(
            self.get_context_data(
                form=form,
                phone_formset=phone_formset,
                email_formset=email_formset,
                address_form=address_form
            ))

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        phone_formset = PhoneFormSet(self.request.POST)
        email_formset = EmailFormSet(self.request.POST)
        address_form = AddAddressForm(self.request.POST)
        if form.is_valid() and phone_formset.is_valid() and email_formset.is_valid() and address_form.is_valid():
            return self.form_valid(form, phone_formset, email_formset, address_form)
        else:
            return self.form_invalid(form, phone_formset, email_formset, address_form)

    def form_valid(self, form, phone_formset, email_formset, address_form):
        self.object = form.save(commit=False)
        self.object = form.save()
        phone_formset.instance = self.object
        phone_formset.save()
        email_formset.instance = self.object
        email_formset.save()
        self.object.address = address_form.save(commit=False)
        self.object.address = address_form.save()
        self.object = form.save()
        return HttpResponseRedirect(reverse_lazy("all"))

    def form_invalid(self, form, phone_formset, email_formset, address_form):
        return self.render_to_response(
            self.get_context_data(form=form,
                                  phone_formset=phone_formset,
                                  email_formset=email_formset,
                                  address_form=address_form))


class ContactEditView(UpdateView):
    model = Person
    fields = ['first_name', 'last_name', 'description', 'groups']
    template_name = "addresses/edit_person.html"
    success_url = reverse_lazy("all")

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        phone_formset = PhoneFormSet(instance=self.object)
        email_formset = EmailFormSet(instance=self.object)
        address_form = AddAddressForm(instance=self.object.address)
        return self.render_to_response(
            self.get_context_data(
                form=form,
                phone_formset=phone_formset,
                email_formset=email_formset,
                address_form=address_form
            ))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        phone_formset = PhoneFormSet(self.request.POST, instance=self.object)
        email_formset = EmailFormSet(self.request.POST, instance=self.object)
        address_form = AddAddressForm(self.request.POST, instance=self.object.address)
        if form.is_valid() and phone_formset.is_valid() and email_formset.is_valid() and address_form.is_valid():
            return self.form_valid(form, phone_formset, email_formset, address_form)
        else:
            return self.form_invalid(form, phone_formset, email_formset, address_form)

    def form_valid(self, form, phone_formset, email_formset, address_form):
        self.object = form.save(commit=False)
        self.object = form.save()
        phone_formset.instance = self.object
        phone_formset.save()
        email_formset.instance = self.object
        email_formset.save()
        address_form.instance = self.object
        address_form.save()
        return HttpResponseRedirect(reverse_lazy("all"))

    def form_invalid(self, form, phone_formset, email_formset, address_form):
        return self.render_to_response(
            self.get_context_data(form=form,
                                  phone_formset=phone_formset,
                                  email_formset=email_formset,
                                  address_form=address_form))


class GetAllPersonsView(View):
    def get(self, request):
        persons = Person.objects.all().order_by("last_name")
        return render(request, "addresses/all.html", locals())


class ContactInfoView(View):
    def get(self, request, id):
        person = Person.objects.get(pk=id)
        phone_numbers = PhoneNumber.objects.filter(person=id)
        emails = EmailAddress.objects.filter(person=id)
        return render(request, "addresses/info.html", locals())


class ContactDeleteView(DeleteView):
    model = Person
    success_url = reverse_lazy("all")


class CreateGroupView(CreateView):
    model = Group
    fields = "__all__"
    success_url = reverse_lazy("all_groups")
    template_name = "addresses/add_group.html"


class GroupListView(ListView):
    model = Group
    template_name = "addresses/all_groups.html"

    def get_queryset(self):
        return Group.objects.annotate(
            members=Count('person', distinct=True)
        )


class GroupInfoView(View):
    def get(self, request, id):
        group = Group.objects.get(pk=id)
        members = Person.objects.filter(groups=group)
        return render(request, "addresses/group_info.html", locals())


class EditGroupView(UpdateView):
    model = Group
    fields = ['group_name', 'group_desc']
    template_name = "addresses/edit_group.html"
    success_url = reverse_lazy("all_groups")


class GroupDeleteView(DeleteView):
    model = Group
    success_url = reverse_lazy("all_groups")

addresses/templates/addresses/add_group.html
{% extends "addresses/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Nowa Grupa</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group mt-2">
                <button class="btn btn-outline-info" type="submit">Zapisz</button>
            </div>
        </form>
    </div>
{% endblock content %}

addresses/templates/addresses/add_person.html
{% extends 'addresses/base.html' %}
{% block content %}
    <form class="form-horizontal" method="POST" action="">
        {% csrf_token %}
        <div class="row spacer">
            <div class="col-2">
                <label>{{ person_form.first_name.label }}</label>
            </div>
            <div class="col-4">
                <div class="input-group">
                    {{ person_form.first_name }}
                </div>
            </div>
        </div>
        <div class="row spacer">
            <div class="col-2">
                <label>{{ person_form.last_name.label }}</label>
            </div>
            <div class="col-4">
                <div class="input-group">
                    {{ person_form.last_name }}
                </div>
            </div>
        </div>
        <div class="row spacer">
            <div class="col-2">
                <label>{{ person_form.description.label }}</label>
            </div>
            <div class="col-4">
                <div class="input-group">
                    {{ person_form.description }}
                </div>
            </div>
        </div>
        {{ email_formset.management_form }}
        {% for m_form in email_formset %}
            <div class="row m_form-row spacer">
                <div class="col-2">
                    <label>{{ m_form.mail.label }}</label>
                </div>
                <div class="col-4">
                    <div class="input-group">
                        {{ m_form.mail }}
                        {{ m_form.m_type }}
                        <div class="input-group-append">
                            <button class="btn btn-success add-m_form-row">+</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
          {{ phone_formset.management_form }}
        {% for p_form in phone_formset %}
            <div class="row p_form-row spacer">
                <div class="col-2">
                    <label>{{ p_form.p_num.label }}</label>
                </div>
                <div class="col-4">
                    <div class="input-group">
                        {{ p_form.p_num }}
                        {{ p_form.p_type }}
                        <div class="input-group-append">
                            <button class="btn btn-success add-p_form-row">+</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="row spacer">
            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-block btn-primary">Dodaj osobę</button>
            </div>
        </div>
    </form>
{% endblock %}

addresses/templates/addresses/all.html
{% extends 'addresses/base.html' %}
{% block content %}
    {% for person in persons %}
        {{ person }}
    {% endfor %}
{% endblock %}

addresses/templates/addresses/all_groups.html
{% extends 'addresses/base.html' %}
{% block content %}
    <div class="content-section">
        <div class="row">
            <div class="container">
                <h1>Lista Grup</h1>
            </div>
        </div>
        <div class="row">
            <div class="container mb-4">
                <table class="table table-secondary">
                    <thead>
                    <tr>
                        <td>Nazwa</td>
                        <td>Opis</td>
                        <td>Członkowie</td>
                        <td>Akcje</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td>{{ object.group_name }}</td>
                            <td>{{ object.group_desc }}</td>
                            <td>{{ object.members }}</td>
                            <td><a href="{% url "group_info" object.id %}">Info</a> | <a
                                    href="{% url "edit_group" object.pk %}">Edytuj</a> | <a
                                    href="{% url "delete_group" object.pk %}">Usuń</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <a class="btn btn-info mb-4" href="{% url 'add_group' %}">Nowa grupa</a>
            </div>
        </div>
    </div>
{% endblock %}

addresses/templates/addresses/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% if title %}
        <title>Adresiki- {{ title }}</title>
    {% else %}
        <title>Adresiki</title>
    {% endif %}
</head>
<body>
<div class="row">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
                    aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <a class="navbar-brand" href="#">Kontakty</a>
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "index" %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "all" %}">Wszystkie kontakty</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "add_person" %}">Nowy kontakt</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "add_group" %}">Nowa grupa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "all_groups" %}">Lista grup</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

<main role="main" class="container">
    <div class="row">
        <div class="col-md-12">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}

        </div>
    </div>
</main>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

<script src="{% static 'adresses/script.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $(".phone_formset").formset({
            prefix: "{{ phone_formset.prefix }}",
        });
        $(".email_formset").formset({
            prefix: "{{ email_formset.prefix }}",
        });
    })
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

addresses/templates/addresses/edit_group.html
{% extends "addresses/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ group_name }}</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group mt-2">
                <button class="btn btn-outline-info" type="submit">Zapisz</button>
            </div>
        </form>
    </div>
{% endblock content %}

addresses/templates/addresses/edit_person.html
{% extends "addresses/base.html" %}
{% block content %}
    <div class="content-section">
        <div class="row">
        <div class="container">
            <h1>Dodaj kontakt</h1>
        </div>
    </div>
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Nowy kontakt</legend>
                {{ form.as_p }}
            </fieldset>
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Adres</legend>
                {{ address_form.as_p }}
            </fieldset>

            <div class="row">
                <fieldset class="col-md-6 mb-4">
                    <legend>Numer Telefonu</legend>
                    {{ phone_formset.management_form }}
                    {{ phone_formset.non_form_errors }}
                    {% for form in phone_formset %}
                        <div class="phone_formset form mb-2">
                            <div class="card">
                                <div  class="card-body">
                                    <small class="text-muted">Phone Number</small>
                                    {{ form.as_p }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </fieldset>

                <fieldset class="col-md-6 mb-4">
                    <legend>Adres email</legend>
                    {{ email_formset.management_form }}
                    {{ email_formset.non_form_errors }}
                    {% for form in email_formset %}
                         <div class="email_formset form mb-2">
                            <div class="card">
                                <div  class="card-body">
                                    <small class="text-muted">Email</small>
                                    {{ form.as_p }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </fieldset>
            </div>

            <div class="form-group mt-2">
                <button class="btn btn-outline-info" type="submit">Zapisz</button>
            </div>
        </form>
    </div>
{% endblock content %}

addresses/templates/addresses/group_confirm_delete.html
{% extends "addresses/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Usuń kontakt</legend>
                <h2>Czy na pewno chcesz usunąć grupę {{ object }}?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Tak, Usuń</button>
                <a class="btn btn-outline-secondary" href="{% url 'group_info' object.id %}">Anuluj</a>
            </div>
        </form>
    </div>
{% endblock content %}

addresses/templates/addresses/group_info.html
{% extends 'addresses/base.html' %}
{% block content %}
    <div class="content-section">
        <div class="row">
            <div class="container">
                <h1>Informacja o grupie</h1>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">{{ group.group_name }}</legend>
                        <p>
                            {{ group.group_desc }}
                        </p>
                </fieldset>
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Członkowie</legend>
                    <ul class="list-group">
                        {% for member in members %}
                            <li class="list-group-item list-group-item-light">
                                {{ member.first_name }} {{ member.last_name }}
                            </li>
                        {% empty %}
                            <li class="list-group-item list-group-item-danger">
                                Grupa jest pusta
                            </li>
                        {% endfor %}
                    </ul>
                </fieldset>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url "edit_group" group.pk %}">Edytuj</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url "delete_group" group.pk %}">Usuń</a>
            </div>
        </div>
    </div>
{% endblock %}

addresses/templates/addresses/index.html
{% extends "addresses/base.html" %}
{% block content %}
    <div class="content-section" style="text-align: center">
        <h1>Książka Adresowa</h1>
        <h4>Wybierz z menu na górze co chcesz zrobić</h4>
    </div>
{% endblock content %}

addresses/templates/addresses/info.html
{% extends 'addresses/base.html' %}
{% block content %}
    <div class="content-section">
        <div class="row">
            <div class="container">
                <h1>Informacja o kontakcie</h1>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">{{ person }}</legend>
                    {% if person.description %}
                        <p>
                            {{ person.description }}
                        </p>
                    {% else %}
                        <p>
                            Brak opisu
                        </p>
                    {% endif %}
                </fieldset>
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Adres</legend>
                    {% if person.address %}
                        <p>
                            {{ person.address.city }}, {{ person.address.street }} {{ person.address.street_number }}
                            m.{{ person.address.flat_number }}
                        </p>
                    {% else %}
                        <p>Brak adresu</p>
                    {% endif %}
                </fieldset>
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Grupy</legend>
                    <ul class="list-group">
                        {% for group in person.groups.all %}
                            <li class="list-group-item list-group-item-light">
                                {{ group.group_name }}
                            </li>
                        {% empty %}
                            <li class="list-group-item list-group-item-danger">
                                Brak grupy
                            </li>
                        {% endfor %}
                    </ul>
                </fieldset>
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Telefony</legend>
                    <ul class="list-group">
                        {% for phone in phone_numbers %}
                            <li class="list-group-item list-group-item-light">
                                {{ phone.p_num }} {{ phone.get_p_type_display }}
                            </li>
                        {% empty %}
                            <li class="list-group-item list-group-item-danger">
                                Brak numeru telefonu
                            </li>
                        {% endfor %}
                    </ul>
                </fieldset>
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Maile</legend>
                    <ul class="list-group">
                        {% for mail in emails %}
                            <li class="list-group-item list-group-item-light">
                                {{ mail.mail }} {{ mail.get_m_type_display }}
                            </li>
                        {% empty %}
                            <li class="list-group-item list-group-item-danger">
                                Brak maila
                            </li>
                        {% endfor %}
                    </ul>
                </fieldset>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'edit_contact' person.id %}">Edytuj</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'delete_contact' person.id %}">Usuń</a>
            </div>
        </div>
    </div>
{% endblock %}

addresses/templates/addresses/person_confirm_delete.html
{% extends "addresses/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Usuń kontakt</legend>
                <h2>Czy na pewno chcesz usunąć {{ object }}?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Tak, Usuń</button>
                <a class="btn btn-outline-secondary" href="{% url 'contact_info' object.id %}">Anuluj</a>
            </div>
        </form>
    </div>
{% endblock content %}